- // MIR for `fn0` before InsertSyncs
+ // MIR for `fn0` after InsertSyncs
  
  fn fn0() -> bool {
      let mut _0: bool;
      let mut _1: i32;
      let mut _2: i32;
      scope 1 {
      }
  
      bb0: {
          StorageLive(_1);
          detach -> [spawned_task: bb1, continuation: bb2];
      }
  
      bb1: {
          StorageLive(_2);
          _2 = const 0_i32;
          _1 = move _2;
          reattach -> bb2;
      }
  
      bb2: {
          StorageDead(_2);
          StorageDead(_1);
          _0 = const true;
+         sync -> bb3;
+     }
+ 
+     bb3: {
          return;
      }
  }
  
