- // MIR for `fn0` before InsertSyncs
+ // MIR for `fn0` after InsertSyncs
  
  fn fn0(_1: bool) -> usize {
      debug x => _1;
      let mut _0: usize;
      let mut _2: i32;
      let mut _3: i32;
      let mut _4: bool;
      scope 1 {
      }
  
      bb0: {
          StorageLive(_2);
          detach -> [spawned_task: bb1, continuation: bb2];
      }
  
      bb1: {
          StorageLive(_3);
          _3 = const 0_i32;
          _2 = move _3;
          reattach -> bb2;
      }
  
      bb2: {
          StorageDead(_3);
          StorageDead(_2);
          StorageLive(_4);
          _4 = _1;
          switchInt(move _4) -> [0: bb4, otherwise: bb3];
      }
  
      bb3: {
          _0 = const 1_usize;
          goto -> bb5;
      }
  
      bb4: {
          _0 = const 2_usize;
          goto -> bb5;
      }
  
      bb5: {
          StorageDead(_4);
+         sync -> bb6;
+     }
+ 
+     bb6: {
          return;
      }
  }
  
